CREATE TABLE IF NOT EXISTS cat_avatar (
  avatar_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  theme_tokens jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS avatar_id integer NULL REFERENCES cat_avatar(avatar_id);

INSERT INTO cat_avatar (code, name, theme_tokens)
VALUES
  ('LEGACY_LOW', 'Legacy Low', jsonb_build_object('accent', '#58CC02', 'chip', 'leaf')),
  ('LEGACY_CHILL', 'Legacy Chill', jsonb_build_object('accent', '#00C2FF', 'chip', 'aqua')),
  ('LEGACY_FLOW', 'Legacy Flow', jsonb_build_object('accent', '#A855F7', 'chip', 'violet')),
  ('LEGACY_EVOLVE', 'Legacy Evolve', jsonb_build_object('accent', '#FF6A00', 'chip', 'ember'))
ON CONFLICT (code) DO UPDATE
SET
  name = EXCLUDED.name,
  theme_tokens = EXCLUDED.theme_tokens,
  is_active = true,
  updated_at = now();

UPDATE users u
SET avatar_id = fallback.avatar_id
FROM cat_game_mode gm
JOIN cat_avatar fallback
  ON fallback.code = CASE gm.code
    WHEN 'LOW' THEN 'LEGACY_LOW'
    WHEN 'CHILL' THEN 'LEGACY_CHILL'
    WHEN 'FLOW' THEN 'LEGACY_FLOW'
    WHEN 'EVOLVE' THEN 'LEGACY_EVOLVE'
    ELSE 'LEGACY_CHILL'
  END
WHERE u.avatar_id IS NULL
  AND u.game_mode_id = gm.game_mode_id;
