import fs from 'node:fs/promises';
import path from 'node:path';
import { pool, endPool } from '../src/db.js';

type Campaign = {
  period_key: string;
  campaign: {
    campaign_code: string;
    title: string;
    objective: string;
    status: string;
    strategy_summary: string;
  };
  posts: Array<Record<string, any>>;
};

type R2Asset = {
  file: string;
  post_code: string;
  r2_key: string;
  public_url: string;
  mime_type: string;
  size_bytes: number;
  sha256: string;
  storage_status: string;
  verified_at: string;
};

type R2Manifest = {
  schema_version: string;
  generated_at: string;
  campaign_code: string;
  github_run_id: string;
  storage_provider: string;
  public_base_url: string;
  asset_count: number;
  assets: R2Asset[];
};

const [campaignPath, manifestPath] = process.argv.slice(2);
if (!campaignPath || !manifestPath) {
  throw new Error('Usage: tsx scripts/import-marketing-campaign-r2.ts <campaign.json> <r2-manifest.json>');
}

const campaign = JSON.parse(await fs.readFile(campaignPath, 'utf8')) as Campaign;
const manifest = JSON.parse(await fs.readFile(manifestPath, 'utf8')) as R2Manifest;
validateManifest(campaign, manifest);
const assetByFile = new Map(manifest.assets.map((asset) => [asset.file, asset]));
const client = await pool.connect();

try {
  await client.query('BEGIN');

  const campaignResult = await client.query<{ marketing_campaign_id: string }>(
    `INSERT INTO marketing_campaigns (period_key, campaign_code, title, objective, status, strategy_summary, source_context)
     VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb)
     ON CONFLICT (campaign_code) DO UPDATE SET
       period_key=EXCLUDED.period_key,title=EXCLUDED.title,objective=EXCLUDED.objective,status=EXCLUDED.status,
       strategy_summary=EXCLUDED.strategy_summary,source_context=EXCLUDED.source_context,updated_at=now()
     RETURNING marketing_campaign_id`,
    [
      campaign.period_key,
      campaign.campaign.campaign_code,
      campaign.campaign.title,
      campaign.campaign.objective,
      campaign.campaign.status,
      campaign.campaign.strategy_summary,
      JSON.stringify({
        campaignJsonPath: campaignPath,
        r2ManifestPath: manifestPath,
        pipeline: {
          creativeDirection: 'complete',
          renderedAt: manifest.generated_at,
          githubRunId: manifest.github_run_id,
          renderedAssetCount: manifest.assets.length,
          storageProvider: 'cloudflare_r2',
          storageStatus: 'verified',
          currentStep: 'review',
        },
      }),
    ],
  );
  const campaignId = campaignResult.rows[0].marketing_campaign_id;

  for (const post of campaign.posts) {
    const postAssets = (post.assets ?? []).map((planned: any) => {
      const filename = planned.asset_code ? `${planned.asset_code}.png` : planned.filename;
      const stored = assetByFile.get(filename);
      if (!stored) throw new Error(`Verified R2 asset missing for ${post.post_code}: ${filename}`);
      if (stored.post_code !== post.post_code) {
        throw new Error(`R2 asset ${filename} belongs to ${stored.post_code}, expected ${post.post_code}`);
      }
      return {
        file: filename,
        title: post.visible_copy_plan?.headline ?? post.hook ?? filename,
        type: planned.asset_kind ?? post.format,
        url: stored.public_url,
        previewUrl: stored.public_url,
        sourceUrl: stored.public_url,
        r2Key: stored.r2_key,
        mimeType: stored.mime_type,
        sizeBytes: stored.size_bytes,
        sha256: stored.sha256,
        storageStatus: stored.storage_status,
        verifiedAt: stored.verified_at,
        selected: true,
      };
    });

    await client.query(
      `INSERT INTO marketing_posts (
         marketing_campaign_id,post_code,platform,format,status,hook,caption,hypothesis,target_metric,tracking_url,
         asset_urls,agent_notes,scheduled_at
       ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12,$13)
       ON CONFLICT (marketing_campaign_id,post_code) DO UPDATE SET
         platform=EXCLUDED.platform,format=EXCLUDED.format,status=EXCLUDED.status,hook=EXCLUDED.hook,
         caption=EXCLUDED.caption,hypothesis=EXCLUDED.hypothesis,target_metric=EXCLUDED.target_metric,
         tracking_url=EXCLUDED.tracking_url,asset_urls=EXCLUDED.asset_urls,agent_notes=EXCLUDED.agent_notes,
         scheduled_at=EXCLUDED.scheduled_at,updated_at=now()`,
      [
        campaignId,
        post.post_code,
        post.platform ?? 'instagram',
        post.format ?? 'static',
        'needs_review',
        post.hook ?? '',
        post.caption ?? '',
        post.hypothesis ?? '',
        post.primary_metric ?? '',
        post.tracking_url ?? '',
        JSON.stringify(postAssets),
        `Imported from verified Cloudflare R2 assets generated by GitHub run ${manifest.github_run_id}.`,
        post.scheduled_at ?? null,
      ],
    );
  }

  await client.query('COMMIT');
  console.log(`Imported ${campaign.posts.length} posts into Admin from ${manifest.assets.length} verified R2 assets for ${campaign.campaign.campaign_code}.`);
} catch (error) {
  await client.query('ROLLBACK');
  throw error;
} finally {
  client.release();
  await endPool();
}

function validateManifest(campaignDocument: Campaign, r2Manifest: R2Manifest) {
  if (r2Manifest.schema_version !== '1.0') throw new Error(`Unsupported R2 manifest schema: ${r2Manifest.schema_version}`);
  if (r2Manifest.storage_provider !== 'cloudflare_r2') throw new Error('R2 manifest storage_provider must be cloudflare_r2');
  if (r2Manifest.campaign_code !== campaignDocument.campaign.campaign_code) {
    throw new Error(`Campaign mismatch: ${r2Manifest.campaign_code} != ${campaignDocument.campaign.campaign_code}`);
  }
  if (!Array.isArray(r2Manifest.assets) || r2Manifest.assets.length === 0) throw new Error('R2 manifest has no assets');
  if (r2Manifest.asset_count !== r2Manifest.assets.length) throw new Error('R2 manifest asset_count does not match assets length');

  const seenFiles = new Set<string>();
  for (const asset of r2Manifest.assets) {
    if (!asset.file || seenFiles.has(asset.file)) throw new Error(`Duplicate or missing R2 asset filename: ${asset.file}`);
    seenFiles.add(asset.file);
    if (asset.storage_status !== 'verified') throw new Error(`R2 asset is not verified: ${asset.file}`);
    if (!/^https:\/\//i.test(asset.public_url)) throw new Error(`R2 asset public_url must be HTTPS: ${asset.file}`);
    if (!/^image\/(png|jpeg|webp)$/i.test(asset.mime_type)) throw new Error(`Unsupported R2 asset MIME: ${asset.file}`);
    if (!Number.isInteger(asset.size_bytes) || asset.size_bytes <= 0) throw new Error(`Invalid R2 asset size: ${asset.file}`);
    if (!/^[a-f0-9]{64}$/i.test(asset.sha256)) throw new Error(`Invalid R2 asset checksum: ${asset.file}`);
    if (!asset.r2_key || !asset.post_code || !asset.verified_at) throw new Error(`Incomplete R2 metadata: ${asset.file}`);
  }

  const plannedFiles = campaignDocument.posts.flatMap((post) =>
    (post.assets ?? []).map((planned: any) => planned.asset_code ? `${planned.asset_code}.png` : planned.filename),
  );
  const missing = plannedFiles.filter((file) => !seenFiles.has(file));
  const unexpected = [...seenFiles].filter((file) => !plannedFiles.includes(file));
  if (missing.length) throw new Error(`R2 manifest is missing planned assets: ${missing.join(', ')}`);
  if (unexpected.length) throw new Error(`R2 manifest contains unexpected assets: ${unexpected.join(', ')}`);
}
