import LegalPageLayout from './LegalPageLayout';

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      subtitle="Source of truth: Docs/legal/terms-of-service.md"
    >
      {/* Keep legal copy in sync with Docs/legal/terms-of-service.md. */}
      <p><strong>Last updated:</strong> 2026-04-11</p>
      <p>
        These Terms of Service (<strong>“Terms”</strong>) govern your access to and use of Innerbloom, including the website,
        mobile applications, and related services (collectively, the <strong>“Service”</strong>).
      </p>
      <p>By creating an account, accessing, or using Innerbloom, you agree to these Terms.</p>

      <section><h2 className="mb-2 text-xl font-semibold">1. Operator</h2><p>Innerbloom is operated by Ramiro Fernandez de Ulllivarri, an individual based in Spain.</p><p>Support: <strong>support@innerbloomjourney.org</strong></p><p>Privacy: <strong>privacy@innerbloomjourney.org</strong></p></section>
      <section><h2 className="mb-2 text-xl font-semibold">2. Eligibility</h2><ul className="list-disc space-y-1 pl-6"><li>you can form a binding agreement under applicable law, and</li><li>you are at least <strong>16 years old</strong>, or the minimum age required by the laws that apply to you.</li></ul></section>
      <section><h2 className="mb-2 text-xl font-semibold">3. The Service</h2><p>Innerbloom is an adaptive habit and self-organization product that may include onboarding flows, tasks, routines, emotional reflections, progress systems, reminders, and related features.</p><p>We may update, modify, improve, suspend, or discontinue parts of the Service from time to time.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">4. Accounts</h2><p>To use certain features, you may need to create an account.</p><p>You agree to provide accurate information, keep your login credentials secure, notify us if you believe your account has been accessed without authorization, and remain responsible for activity that occurs under your account, unless prohibited by law.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">5. Acceptable use</h2><p>You agree not to:</p><ul className="list-disc space-y-1 pl-6"><li>use the Service for unlawful, fraudulent, or abusive purposes</li><li>interfere with or disrupt the Service</li><li>attempt to gain unauthorized access to systems or accounts</li><li>copy, reverse engineer, scrape, or exploit the Service except as allowed by law</li><li>upload or transmit malicious code</li><li>use the Service to harass, harm, or violate the rights of others</li></ul><p>We may suspend or terminate access if we reasonably believe you have violated these Terms or created risk for the Service or other users.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">6. User content and data</h2><p>You may submit information to the Service, including onboarding responses, habit data, progress records, reflections, or other inputs (<strong>“User Content”</strong>).</p><p>You retain ownership of your User Content. However, you grant us the rights reasonably necessary to host, process, store, reproduce, adapt, and display that content for the purpose of operating, maintaining, and improving the Service.</p><p>You are responsible for ensuring that you have the rights needed to submit any content you provide.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">7. Privacy</h2><p>Our handling of personal information is described in the Privacy Policy. By using the Service, you acknowledge that your information may be processed as described there.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">8. Subscriptions, billing, and paid features</h2><p>Certain features of Innerbloom may be offered on a paid basis, including subscriptions or premium access.</p><p>If paid features are offered, pricing, billing terms, and renewal mechanics will be shown before purchase, you authorize the applicable payment provider to charge the selected payment method, and fees are generally non-refundable except where required by law or expressly stated otherwise.</p><p>If mobile in-app purchases are later introduced, those purchases may also be subject to Apple App Store or Google Play billing terms.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">9. No medical, psychological, therapeutic, legal, or financial advice</h2><p>Innerbloom is intended for general informational, organizational, motivational, and habit-building purposes.</p><p>Innerbloom is <strong>not</strong> a medical device and does <strong>not</strong> provide medical, psychiatric, psychological, therapeutic, legal, financial, or other professional advice. The Service is not intended to diagnose, treat, cure, or prevent any disease or condition.</p><p>You should seek qualified professional advice for medical, mental health, legal, financial, or other professional matters.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">10. Availability and changes</h2><p>We do not guarantee that the Service will always be available, uninterrupted, secure, or error-free.</p><p>We may change the Service, including features, designs, eligibility, pricing, or availability, at any time.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">11. Intellectual property</h2><p>The Service, including its software, branding, visual design, text, graphics, interfaces, and related materials, is owned by or licensed to Innerbloom and is protected by intellectual property laws.</p><p>Except for the limited right to use the Service under these Terms, no rights are granted to you.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">12. Termination</h2><p>You may stop using the Service at any time.</p><p>We may suspend or terminate your access if you violate these Terms, we are required to do so by law, continued access creates legal, security, or operational risk, or we discontinue the Service.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">13. Disclaimers</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS.</p><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">14. Limitation of liability</h2><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, INNERBLOOM AND ITS OPERATOR, AFFILIATES, SERVICE PROVIDERS, AND LICENSORS WILL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITY, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE.</p><p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR CLAIMS ARISING OUT OF OR RELATED TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US FOR THE SERVICE IN THE 12 MONTHS BEFORE THE CLAIM AROSE, OR EUR 100 IF YOU HAVE NOT PAID US ANYTHING, UNLESS APPLICABLE LAW REQUIRES OTHERWISE.</p><p>Some jurisdictions do not allow certain limitations, so parts of this section may not apply to you.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">15. Governing law</h2><p>These Terms are governed by the laws of <strong>Spain</strong>, without regard to conflict of law principles, except where mandatory law in your jurisdiction requires otherwise.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">16. Changes to these Terms</h2><p>We may update these Terms from time to time. When we do, we will update the “Last updated” date above. Continued use of the Service after updated Terms become effective means you agree to the updated Terms, to the extent permitted by law.</p></section>
      <section><h2 className="mb-2 text-xl font-semibold">17. Contact</h2><p>Support: <strong>support@innerbloomjourney.org</strong></p><p>Privacy: <strong>privacy@innerbloomjourney.org</strong></p></section>
    </LegalPageLayout>
  );
}
